services:
  replay:
    container_name: mi-nas-camera-replay
    image: hesier/mi-nas-camera-replay:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - ./.env
    volumes:
      - ${HOST_VIDEO_ROOT_1:-./videos/cam1}:/videos/cam1:ro
      - ${HOST_VIDEO_ROOT_2:-./videos/cam2}:/videos/cam2:ro
      - ${HOST_DATA_DIR:-./data}:/app/backend/data
